publications/urls.py
from django.conf.urls import url
from .views import NewPublicationView, PublicationView, FilterView

app_name = 'publications'

urlpatterns = [
    url(r'^new/$', NewPublicationView.as_view(), name='new'),
    url(r'^edit/(?P<pub_id>[0-9]+)/$', NewPublicationView.as_view(), name='edit'),
    url(r'view/(?P<pub_id>[0-9]+)/$', PublicationView.as_view(), name='view'),
    url(r'filter/$', FilterView.as_view(), name='filter')
]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    url(r'^pprofile/', include('p_profile.urls')),
    url(r'^publication/', include('publications.urls')),
]

publications/models.py
from django.db import models
from django.contrib.auth.models import User

class ResearchField(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Publication(models.Model):

    pub_type_choices = (
        ('1', 'Journal'),
        ('2', 'Confrance'),
        ('3', 'Book'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    research_field = models.ForeignKey(ResearchField, on_delete=models.CASCADE)
    authors = models.CharField(max_length=100)
    national = models.BooleanField(default=False)
    date = models.IntegerField(default=0)
    pub_type = models.CharField(max_length=10, choices=pub_type_choices)
    details = models.CharField(max_length=500)
    identifier = models.CharField(max_length=50, null=True, blank=True)
    abstract = models.CharField(max_length=1000)
    
    def __str__(self):
        return self.title

publications/temp/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render, Http404
from django.views import View
from django.http import Http404
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from .models import Publication, ResearchField
from p_profile.models import ProfessorProfile

login_redirect_url = getattr(settings, 'LOGIN_URL', 'accounts:login')

class NewPublicationView(View):
    @method_decorator(login_required(login_url=login_redirect_url))
    def get(self, request, pub_id='-1'):
        if not ProfessorProfile.objects.filter(user=request.user).exists():
            return redirect('p_profile:create')

        context = {}
        if not pub_id == '-1':
            obj = get_object_or_404(Publication, id=pub_id)

            if not request.user == obj.user:
                raise Http404

            context = {
                'title': obj.title,
                'research_field': obj.research_field,
                'authors':obj.authors,
                'national':obj.national,
                'date':obj.date,
                'pub_type': obj.pub_type,
                'details': obj.details,
                'identifier': obj.identifier,
                'abstract': obj.abstract,
            }
        context['fields'] = ResearchField.objects.all()
        context['years'] = range(1980, timezone.now().year+1)
        return render(request, 'publications/create.html', context) #TODO

    @method_decorator(login_required(login_url=login_redirect_url))
    def post(self, request, pub_id='-1'):
        if not ProfessorProfile.objects.filter(user=request.user).exists():
            return redirect('p_profile:create')

        if not pub_id == '-1':
            pub = get_object_or_404(Publication, id=pub_id)
            if not request.user == pub.user:
                raise Http404

        errors = []
        try:
            title = request.POST.get('title')
            research_field = request.POST.get('research_field')
            authors = request.POST.get('authors')
            national = request.POST.get('national')
            date = request.POST.get('year')
            pub_type = request.POST.get('published_in')
            try:
                details = request.POST.getlist('details')[int(pub_type) - 1]
            except:
                details = ''
            identifier = request.POST.getlist('identifier')
            abstract = request.POST.get('abstract')

            if pub_type == '1':
                identifier = identifier[0]
            elif pub_type == '3':
                identifier = identifier[1]
            else:
                identifier = 'None'

            context = {
                'errors': errors,
                'fields': ResearchField.objects.all(),
                'title': title,
                'authors':authors,
                'national':national,
                'date':date,
                'published_in': pub_type,
                'details': details,
                'identifier': identifier,
                'abstract': abstract,
                'years': range(1980, timezone.now().year+1),
            }

            try:
                context['research_field'] = get_object_or_404(ResearchField, name=research_field)
            except:
                context['research_field'] = ''

            if title and research_field and authors and national and date and pub_type and details: # and identifier and abstract:

                if not pub_id=='-1':
                    obj = get_object_or_404(Publication, id=pub_id)
                else:
                    obj = Publication()
                obj.user = request.user
                obj.title = title
                obj.research_field = get_object_or_404(ResearchField, name=research_field)
                obj.authors = authors
                obj.national = (national == "National")
                obj.date = date
                obj.pub_type = pub_type
                obj.details = details
                obj.identifier = identifier
                obj.abstract = abstract
                obj.save()

                return redirect('publications:view', pub_id = obj.id) #TODO
            else:
                if title == '':
                    errors.append('Title field cannot be empty.')
                if research_field == '':
                    errors.append('Research field cannot be empty.')
                if authors == '':
                    errors.append('Authors field cannot be empty.')
                if national == '':
                    errors.append('National/International field cannot be empty.')
                if date == '':
                    errors.append('Publication year cannot be empty.')
                if pub_type == None:
                    errors.append('Published in type cannot be empty.')
                if not details:
                    errors.append('Published in details cannot be empty.')
                # if not identifier:
                #     errors.append('Identifier field cannot be empty.')
                # if abstract == '':
                #     errors.append('Abstract field cannot be empty.')
                return render(request, 'publications/create.html', context) #TODO
        except:
            raise Http404

class PublicationView(View):
    @method_decorator(login_required(login_url=login_redirect_url))
    def get(self, request, pub_id):
        obj = get_object_or_404(Publication, id=pub_id)
        if not obj.user == request.user and not request.user.groups.filter(name='supervisor').exists():
            raise Http404()

        return render(request, 'publications/view_v2.html', {'publication': obj, 'can_change': obj.user == request.user})

class FilterView(View):
    @method_decorator(login_required(login_url=login_redirect_url))
    def get(self, request):
        if not request.user.groups.filter(name='supervisor').exists():
            raise Http404

        print_pub = request.GET.get('print', '')
        title = request.GET.get('title', '')
        authors = request.GET.get('authors', '')
        research_field = request.GET.get('research_field', '')
        nationality = request.GET.get('national', 'international')
        publication_year = request.GET.get('year')
        published_in = request.GET.getlist('published_in')
        journal_details = request.GET.get('journal_details', '')
        confrance_details = request.GET.get('confrance_details', '')
        book_details = request.GET.get('book_details', '')
        journal_id = request.GET.get('journal_identifier', '')
        book_id = request.GET.get('book_identifier', '')
        abstract = request.GET.get('abstract', '')

        pubs = Publication.objects.order_by('id')
        
        pubs = pubs.filter(title__contains=title)
        pubs = pubs.filter(authors__contains=authors)
        pubs = pubs.filter(research_field__name__contains=research_field)
        if publication_year:
            print('ye')
            pubs = pubs.filter(date=publication_year)
        pubs = pubs.filter(abstract__contains=abstract)
        if len(published_in) > 0:
            pubs = pubs.filter(pub_type__in=published_in)

        if nationality == 'International':
            pubs = pubs.filter(national=False)
        elif nationality == 'National':
            pubs = pubs.filter(national=True)

        filtered_pubs = []
        if 1 in published_in or '1' in published_in:
            filtered_pubs.extend(list(pubs.filter(pub_type='1', details__contains=journal_details, identifier__contains=journal_id)))
        if 2 in published_in or '2' in published_in:
            filtered_pubs.extend(list(pubs.filter(pub_type='2', details__contains=confrance_details)))
        if 3 in published_in or '3' in published_in:
            filtered_pubs.extend(list(pubs.filter(pub_type='3', details__contains=book_details, identifier__contains=book_id)))
        
        if len(filtered_pubs) == 0:
            filtered_pubs = pubs

        context = {
            'publications': filtered_pubs,
            'title': title,
            'authors': authors,
            'research_field': research_field,
            'nationality': nationality,
            'publication_year': publication_year,
            'published_in':published_in,
            'journal_details':journal_details,
            'confrance_details':confrance_details,
            'book_details':book_details,
            'journal_id':journal_id,
            'book_id':book_id,
            'abstract': abstract,
            'fields': ResearchField.objects.all(),
            'years': range(1980, timezone.now().year+1),
        }

        if print_pub == 'print':
            return render(request, 'publications/print.html', context)
        else:
            return render(request, 'publications/filter.html', context)

publications/templates/publications/filter.html
{% extends "header.html" %}

{% block title %} Filter publications {%endblock%}

{% block content %}
<section class="container table-page">
    {% include "navbar.html" %}
    <div class="main">
        <header class="text-center">
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <h1>Publications</h1>
                </div>
                <div class="col-md-4">
                    <div class="pull-right" style="margin-top:25px;">
                        <a class="btn filter-Toggle" style="display: inline;">Show/Hide Filter</a>
                        <a class="btn" onclick="location.href='{% url 'publications:filter' %}';" style="display: inline;">Clear filter</a>
                    </div>
                </div>
            </div>
        </header>
        <form id="publication_form" class="filter-publication" method="GET" action="">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Title:-</label>
                        <input class="form-control" type="text" name="title" placeholder="Title" value="{{title}}">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Authors:-</label>
                        <input class="form-control" type="text" name="authors" placeholder="Authors" value="{{authors}}">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Research field:-</label>
                        <select class="selectpicker" data-live-search="true" title="Choose research field" name="research_field">
                            {% for field in fields %}
                                <option {% if field.name == research_field %}selected="selected" {%endif%}>{{field.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Nationality:-</label>
                        <select class="selectpicker" data-live-search="true" title="Choose" name="national">
                            <option {% if nationality == 'Any' or nationality == '' %} selected="selected" {%endif%}>Any</option>
                            <option {% if nationality == 'National' %} selected="selected" {%endif%}>National</option>
                            <option {% if nationality == 'International' %} selected="selected" {%endif%}>International</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Publication year:-</label>
                        <select class="selectpicker" data-live-search="true" title="Choose publication year" name="year">
                            {% for year in years %}
                                <option {% if publication_year == year %} selected="selected" {%endif%}>{{year}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Published In:-</label>
                        <div class="checkbox-group">
                            <!--Jonfrance-->
                            <input type="checkbox" id="jonfrance" name="published_in" class="material-checkbox" data-target="jonfrance" value="1">
                            <label class="checkbox_label" for="jonfrance">Journal</label>
                            <div class="jonfrance hidde">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input class="form-control" type="text"name="journal_details" placeholder="Journal Name" value="{{journal_details}}">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input class="form-control" type="text" name="journal_identifier" placeholder="DOI" value="{{journal_identifier}}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--Confrance-->
                            <input type="checkbox" id="confrance" data-target="confrance" name="published_in" class="material-checkbox" value="2">
                            <label class="checkbox_label" for="confrance">Confrance</label>
                            <div class="confrance hidde">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input class="form-control" type="text" name="confrance_details" placeholder="Confrance Details" value="{{confrance_details}}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--Book-->
                            <input type="checkbox" id="book" name="published_in" class="material-checkbox" data-target="book" value="3">
                            <label class="checkbox_label" for="book">Book</label>
                             <div class="book hidde">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input class="form-control" type="text" name="book_details" placeholder="Book Name" value="{{book_details}}">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input class="form-control" type="text" name="book_identifier" placeholder="ISSN" value="{{book_identifier}}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Abstract:-</label>
                        <textarea class="form-control" name="abstract" style="resize:vertical;">{{abstract}}</textarea>
                    </div>
                </div>
                <div class="col-md-6">
                    <button type="submit" class="btn btn-block">Filter</button>
                </div>
            </div>
        </form>
        <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Title</th>
                <th>Authors</th>
                <th>Publication year</th>
            </tr>
            </thead>
            <!-- <tfoot>
            <tr>
                <th>Title</th>
                <th>Authors</th>
                <th>Publication year</th>
            </tr>
            </tfoot> -->
            <tbody>
                {% for publication in publications %}
                    <tr onclick="location.href='{% url 'publications:view' publication.id %}'" class="pointer-on-hover">
                        <td>{{publication.title|truncatechars:90}}</td>
                        <td>{{publication.authors|truncatechars:30}}</td>
                        <td>{{publication.date}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="" onclick="printData();" class="print text-center"> Print <i class="fa fa-print"></i></a>
    </div>
</section>
<section class="container">
        
</section>
{% endblock %}

{% block script %}
<script type="text/javascript">
    $('#example').DataTable({
        responsive: {
            orthogonal: 'responsive'
        }
    });
</script>
<script>
    $(function(){
        {% for pub_type in published_in %}
            {% if pub_type == '1' %}
                $('#jonfrance').click();
            {% elif pub_type == '2' %}
                $('#confrance').click();
            {% elif pub_type == '3' %}
                $('#book').click();
            {% endif %}
        {% endfor %}
    })

    function printData()
    {
        var extra = "&print=print"
        if(location.href.endsWith('/'))
            extra = "?" + extra;
        newWin= window.open(location.href + extra);
    }

    $('.filter-Toggle').on('click', function () {
        $('.filter-publication').slideToggle();
    })
</script>
{% endblock %} 

publications/templates/publications/print.html
{% extends "print_header.html" %}

{% block title %} Print publications {%endblock%}

{% block content %}
<style>
    @page { size: auto;  margin: 0mm; }
    .table-bordered>tbody>tr>td{
        word-break: break-word;
        /* width: 100px; */
        overflow: hidden;
    }
</style>
    <table id="example" class="table table-stripped table-bordered" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Field</th>
                <th>Title</th>
                <th>Authors</th>
                <th>Nationality</th>
                <th>Year</th>
            </tr>
            </thead>
            <tbody>
                {% for publication in publications %}
                    <tr>
                        <td>{{publication.research_field.name}}</td>
                        <td>{{publication.title}}</td>
                        <td>{{publication.authors}}</td>
                        <td>{% if publication.national %} National {%else%} International {%endif%}</td>
                        <td>{{publication.date}}</td>
                    </tr>
                {% endfor %}
            </tbody>
    </table>
{% endblock %}

{% block script %}

<script>
    $(function(){
        window.print();
    });
</script>
{%endblock%}

publications/templates/publications/view_v2.html
{% extends "header.html" %}

{% block title %} Add new publication {%endblock%}

{% block content %}
<section class="container">
    <div class="publication creat-publication">
		{% include "navbar.html" %}
        <div class="box-form">
            <div class="header">
                <h3>Publication</h3>
            </div>
            <form id="form-publication">
                <div class="row">
                    <div class="col-md-6">
                        <div class="details-creat">
                            <label>Title:-</label>
                            <p>{{publication.title}}</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="details-creat">
                            <label>Authors:-</label>
                            <p>{{publication.authors}}</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="details-creat">
                            <label>Research field:-</label>
                            <p>{{publication.research_field.name}}</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="details-creat">
                            <label>Nationality:-</label>
                            <p>{% if publication.national %}National{%else%}International{%endif%}</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="details-creat">
                            <label>Publication year:-</label>
                            <p>{{publication.date}}</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="details-creat">
                            <label>Published in:-</label>
                            <p>{{publication.get_pub_type_display}}</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="details-creat">
                            <label>{% if publication.pub_type == '1' %} Journal {% elif publication.pub_type == '2' %} Conference {% elif publication.pub_type == '3' %} Book {%endif%} {% if publication.pub_type == '2' %}Details{% else %}Name{% endif %}:-</label>
                            <p>{{publication.details}}</p>
                        </div>
                    </div>
                    {% if publication.pub_type != '2' %}
                        <div class="col-md-6">
                            <div class="details-creat">
                                <label>Identifier (DOI, ISSN):-</label>
                                <p>{{publication.identifier}}</p>
                            </div>
                        </div>
                    {% endif %}
                    <div class="col-md-12">
                        <div class="details-creat">
                            <label>Abstract:-</label>
                            <p class="abstract">{{publication.abstract}}</p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        {% if can_change %}
                            <a href="{% url 'publications:edit' publication.id %}" class="btn"><i class="fa fa-cloud-upload"></i> Change</a>
                        {%endif%}
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}