p_profile/urls.py
from django.conf.urls import url
from .views import CreateProfessorProfileView, ProfessorProfileView

app_name = 'p_profile'

urlpatterns = [
    url(r'^create/$', CreateProfessorProfileView.as_view(), name='create'),
    url(r'^view/$', ProfessorProfileView.as_view(), name='view'),
    #url(r'^edit/$', CreateProfessorProfileView.as_view(), name='edit', kwargs={'edit':True}),
]

publications/urls.py
from django.conf.urls import url
from .views import NewPublicationView, PublicationView, FilterView

app_name = 'publications'

urlpatterns = [
    url(r'^new/$', NewPublicationView.as_view(), name='new'),
    url(r'^edit/(?P<pub_id>[0-9]+)/$', NewPublicationView.as_view(), name='edit'),
    url(r'view/(?P<pub_id>[0-9]+)/$', PublicationView.as_view(), name='view'),
    url(r'filter/$', FilterView.as_view(), name='filter')
]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    url(r'^pprofile/', include('p_profile.urls')),
    url(r'^publication/', include('publications.urls')),
]

p_profile/models.py
from django.db import models
from django.contrib.auth.models import User

class Department(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Affiliation(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class ProfessorProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    speciality = models.CharField(max_length=100)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    affiliation = models.ForeignKey(Affiliation, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

p_profile/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Affiliation, Department, ProfessorProfile
from publications.models import Publication

login_redirect_url = getattr(settings, 'LOGIN_URL', 'accounts:login')


class CreateProfessorProfileView(View):
    @method_decorator(login_required(login_url=login_redirect_url))
    def get(self, request, edit=False):
        if ProfessorProfile.objects.filter(user=request.user).exists():
            return redirect('p_profile:view')
        
        context = {
            'affiliations': Affiliation.objects.all(),
            'departments': Department.objects.all(),
        }
        if edit == True:
            obj = get_object_or_404(ProfessorProfile, user=request.user)
            context = {
                'affiliations': Affiliation.objects.all(),
                'departments': Department.objects.all(),
                'name': obj.name,
                'speciality': obj.speciality,
                'department': obj.department,
                'affiliation': obj.affiliation,
            }

        return render(request, 'pprofile/create.html', context) #TODO

    @method_decorator(login_required(login_url=login_redirect_url))
    def post(self, request):
        errors = []
        name = request.POST.get('name')
        speciality = request.POST.get('speciality')
        department = request.POST.get('department')
        affiliation = request.POST.get('affiliation')

        context = {
            'affiliations': Affiliation.objects.all(),
            'departments': Department.objects.all(),
            'name': name,
            'speciality': speciality,
            'department': department,
            'affiliation': affiliation,
            'errors': errors,
        }

        if name and speciality and department and affiliation:
            if ProfessorProfile.objects.filter(user=request.user).exists():
                obj = ProfessorProfile.objects.get(user=request.user)
            else:
                obj = ProfessorProfile()
            obj.user = request.user
            obj.name = name
            obj.speciality = speciality
            obj.department = get_object_or_404(Department, name=department)
            obj.affiliation = get_object_or_404(Affiliation, name=affiliation)
            obj.save()
            return redirect('p_profile:view')
        else:
            if name == '':
                errors.append('Name field cannot be empty!')
            if speciality == '':
                errors.append('Speciality field cannot be empty!')
            if department == '':
                errors.append('Department field cannot be empty!')
            if affiliation == '':
                errors.append('Affiliation field cannot be empty!')
            return render(request, 'pprofile/create.html', context) # TODO


class ProfessorProfileView(View):
    @method_decorator(login_required(login_url=login_redirect_url))
    def get(self, request):
        if not ProfessorProfile.objects.filter(user=request.user).exists():
            return redirect('p_profile:create')
        
        # if request.user.groups.filter(name='supervisor').exists():
        #     paginator = Paginator(Publication.objects.order_by('-id'), 10)
        # else:
        paginator = Paginator(Publication.objects.filter(user=request.user).order_by('-id'), 10)

        page = request.GET.get('page')

        try:
            publications = paginator.page(page)
        except PageNotAnInteger:
            publications = paginator.page(1)
        except EmptyPage:
            publications = paginator.page(paginator.num_pages)

        context = {
            'profile': get_object_or_404(ProfessorProfile, user=request.user),
            'publications': publications,
        }



        return render(request, 'pprofile/view_2.html', context)

p_profile/templates/pprofile/create.html
{% extends "header.html" %}

{% block title %} Create your profile {%endblock%}

{% block content %}
    <section class="profile">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-2 col-md-8">
                    {% include "navbar.html" %}
                    <div class="box-form">
                        <div class="header">
                            <h3>Profile</h3>
                        </div>
                        {% if errors %}
                            <div class="alert alert-danger" role="alert">
                                {% for error in errors %}
                                    {{error}} <br/>
                                {% endfor %}
                            </div>
                        {% endif %}
                        <form method="POST" action="" id="profile_form">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Name:- </label>
                                        <input
                                            class="form-control"
                                            type="text"
                                            name="name"
                                            placeholder="Your Name"/>
                                            <!-- alert error-->
                                        <div class="custom-alert">this field is requird *</div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Speciality:-</label>
                                        <input
                                            class="form-control"
                                            type="text"
                                            name="speciality"
                                            placeholder="Your Speciality">
                                        <!-- alert error-->
                                        <div class="custom-alert">this field is requird *</div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Department:-</label>
                                        <select class="selectpicker" name="department" data-live-search="true" title="Choose Your Department">
                                            {% for dep in departments %}
                                                <option>{{dep.name}}</option>
                                            {% endfor %}
                                        </select>

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Affiliation:-</label>
                                        <select class="selectpicker" data-live-search="true" name="affiliation" title="Choose your affiliation">
                                            {% for afl in affiliations %}
                                            <option>{{afl.name}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-block">Next</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{%endblock%}

p_profile/templates/pprofile/view.html
{% extends "header.html" %}

{% block title %} {{profile.name}} Profile {%endblock%}

{% block content %}
    <section class="profile">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-2 col-md-8">
                    <div class="box-form">
                        <div class="header">
                            <h3>Profile</h3>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Name:- </label>
                                    <label>{{profile.name}}</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Speciality:-</label>
                                    <label>{{profile.speciality}}</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Department:-</label>
                                    <label>{{profile.department.name}}</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Affiliation:-</label>
                                    <label>{{profile.affiliation.name}}</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br/><br/><br/>
            <div class="row">
                <div class="col-md-offset-2 col-md-8">
                    <div class="list-research">
                        <div class="header">
                            <h3><i class="fa fa-file-text-o"></i> List Of Publications</h3>
                        </div>
                        <ul class="list-unstyled">
                            {% for publication in publications %}
                            <li><a href="{% url 'publications:view' publication.id %}">{{publication.title}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- TODO Should probably use bootstrap pagination here -->
                    {% if publications.has_previous %}
                    <div class="pull-left">
                        <button class="btn" onclick="location.href='?page={{publications.previous_page_number}}'"><<</button>
                    </div>
                    {% endif %}
                    <div class="text-center block-center">
                        Page {{publications.number}} / {{publications.paginator.num_pages}}
                    </div>
                    <div class="pull-right">
                        {% if publications.has_next %}
                            <button class="btn" onclick="location.href='?page={{publications.next_page_number}}'">>></button>
                        {% endif %}
                        <button class="btn" onclick="location.href='{% url 'publications:new' %}'">Add new publication</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
{%endblock%}

p_profile/templates/pprofile/view_2.html
{% extends "header.html" %}

{% block title %} {{profile.name}} Profile {%endblock%}

{% block content %}
<section class="profile creat-profile">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="list-research">
                    <div class="header">
                        <h3><i class="fa fa-file-text-o"></i> List Of Publications</h3>
                    </div>
                    <ul class="list-unstyled">
                        {% for publication in publications %}
                        <li><a href="{% url 'publications:view' publication.id %}">{{publication.title|truncatechars:30}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- TODO Should probably use bootstrap pagination here -->
                {% if publications.has_previous %}
                <div class="pull-left">
                    <button class="btn" onclick="location.href='?page={{publications.previous_page_number}}'"><<</button>
                </div>
                {% endif %}
                <div class="text-center block-center">
                    <font color=white>Page {{publications.number}} / {{publications.paginator.num_pages}}</font>
                </div>
                <div class="pull-right">
                    {% if publications.has_next %}
                        <button class="btn" onclick="location.href='?page={{publications.next_page_number}}'">>></button>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-8">
				{% include "navbar.html" %}
                <div class="box-form">
                    <div class="header">
                        <h3>Profile</h3>
                    </div>
                    <form>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="details-creat">
                                    <label>Name:-</label>
                                    <p>{{profile.name}}</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="details-creat">
                                    <label>Speciality:-</label>
                                    <p>{{profile.speciality}}</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="details-creat">
                                    <label>Department:-</label>
                                    <p>{{profile.department.name}}</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="details-creat">
                                    <label>Affiliation:-</label>
                                    <p>{{profile.affiliation.name}}</p>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <!-- <a href="{% url 'publications:new' %}" class="btn">New publication</a> -->
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{%endblock%}